name: Build and Release

on:
  push:
    branches: [ master ]

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm run build
      - name: Get package version
        id: package_version
        run: echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.package_version.outputs.version }}
          files: dist/gremlins.min.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
